name: python
on: push #trigger
jobs:
  run_tests:
   runs-on: ubuntu-latest
    steps:
         -name: checkout repo content
         uses: action/checkout@v2
         -name: setup python
         uses: action/setup-python@v2
         -name: run script
         run: python test.py
